In [2]:
!pip install numpy

# 1D Array

In [3]:
import numpy as np

arr=np.array([1,2,3])
print(arr)

[1 2 3]


# 2D Array

In [4]:
arr=np.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3D Array

In [5]:
arr=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# 4D Array

In [6]:
arr=np.array([[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]])
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# 5D Array

In [7]:
arr=np.array([[[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]],[[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]]])
print(arr)

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]


  [[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]



 [[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]


  [[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]]


# Initial Placeholders

In [8]:
#Create an array of zeros
arr=np.array(np.zeros(3))
print(arr)

[0. 0. 0.]


In [9]:
arr=np.array(np.zeros((3,4)))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
arr=np.array(np.zeros((2,3,4)))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [11]:
#Create an array of ones
arr=np.array(np.ones((2,3,4)))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [12]:
#Create an array of evenly spaced values (step value)
a=np.arange(5,25,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23]


In [13]:
#Create an array of evenlyspaced values (number of samples)
b=np.linspace(1,10,10)
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [14]:
#Create a constant array
#Create a 1D array
c=np.full((2,3),7)
print(c)
print(c.ndim)

[[7 7 7]
 [7 7 7]]
2


In [15]:
d=np.full((2,2,3),7)
print(d)
print(d.ndim)

[[[7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]]]
3


In [16]:
#Create a 2X2 identity matrix
e=np.eye(1)
print(e)

[[1.]]


In [17]:
e=np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


In [18]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#Create an array with random values
np.random.random(3)

array([0.34835159, 0.7832701 , 0.79021434])

In [20]:
np.random.random((3,4))

array([[0.54814   , 0.18563433, 0.33571306, 0.35129565],
       [0.62256123, 0.46438058, 0.96669336, 0.12330465],
       [0.87747557, 0.11468468, 0.38958222, 0.34274161]])

In [21]:
np.random.random((2,3,4))

array([[[0.69182198, 0.17327166, 0.1906692 , 0.4389173 ],
        [0.71520066, 0.43553023, 0.49073617, 0.12113302],
        [0.66845923, 0.1746303 , 0.73975128, 0.10737628]],

       [[0.92043149, 0.83976334, 0.40464798, 0.75050094],
        [0.47061862, 0.81888836, 0.33461466, 0.74536317],
        [0.64014696, 0.92187483, 0.12373023, 0.25379177]]])

In [22]:
arr=np.array([1,2,3])
print(arr.shape) #to find shape of an Array i.e (no. of rows,no. of cols)
print(arr.size) #To Find NO of elements in array
len(arr) #To Find len of array i.e # It Will count only the rows

(3,)
3


3

In [23]:
arr=np.array([(1,2,3),(4,5,6)])
print(arr.shape)
print(arr.size)
len(arr)

(2, 3)
6


2

In [24]:
arr=np.array([[(1,2,3),(4,5,6)],
 [(7,8,9),(10,11,12)]])
print(arr.shape)
print(arr.size)
len(arr)

(2, 2, 3)
12


2

In [25]:
arr=np.array([[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],
 [[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]])
print(arr.shape)
print(arr.size)
len(arr)

(2, 2, 2, 3)
24


2

In [26]:
arr=np.array([[[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]],
 [[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]]])
print(arr.shape)
print(arr.size)
len(arr)

(2, 2, 2, 2, 3)
48


2

In [27]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [5, 7, 7, 8]])
print(arr.shape)
print(arr.size)
len(arr)

(3, 4)
12


3

In [28]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [5, 6, 7, 8],
                [5, 7, 7, 8]])
print(arr.shape)
print(arr.size)
len(arr)

(4, 4)
16


4

In [29]:
np.random.randint(5,8)

6

# Access Array Elements

In [31]:
arr=np.array([1,2,3,4])
print(arr[3])

4


In [33]:
arr=np.array([[1,2,3,4],
             [5,6,7,8]])
print(arr[0,3])

4


In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])
print(arr[1,1,2])

12


In [34]:
arr=np.array([1,2,3,4])
arr=np.array([5,6,7,8])
print(arr[3]+arr[2])

15


# Data Types

In [40]:
arr=np.array([4,5,6,7,8,9],dtype='S')
print(arr)
print(arr.dtype)

[b'4' b'5' b'6' b'7' b'8' b'9']
|S1


In [41]:
arr=np.array([4,5,6,7,8,9],dtype='i4')
print(arr)
print(arr.dtype)

[4 5 6 7 8 9]
int32


In [44]:
arr=np.array([10,11,12,13],dtype='i8')
print(arr)
print(arr.dtype)

[10 11 12 13]
int64


In [47]:
arr=np.array([2.1,5.3,5.7])
newarr=arr.astype('i')
print(arr)
print(newarr)

[2.1 5.3 5.7]
[2 5 5]


In [48]:
arr=np.array([2.1,5.3,5.7])
newarr=arr.astype(bool)
print(arr)
print(newarr)

[2.1 5.3 5.7]
[ True  True  True]


In [49]:
arr=np.array([3,4,6,8])
copyarr=arr.copy()
arr[2]=20
print(arr)
print(copyarr)

[ 3  4 20  8]
[3 4 6 8]


In [50]:
arr=np.array([3,4,6,8])
copyarr=arr.view()
arr[2]=20
print(arr)
print(copyarr)

[ 3  4 20  8]
[ 3  4 20  8]


In [53]:
arr=np.array([[3,4,6,8],[3,5,6,8]])
print(arr.shape)

(2, 4)


# Reshaping Array

In [55]:
#Converting 1D to 2D
arr=np.array([1,2,3,4])
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [56]:
#Converting 1D to 3D
arr=np.array([1,2,3,4,5,6,7,8])
arr.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [57]:
#Converting 2D to 1D
arr=np.array([[1, 2],
              [3, 4]])
arr.reshape(4)

array([1, 2, 3, 4])

In [58]:
#Converting 3D to 1D
arr=np.array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])
arr.reshape(8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
#Converting 2D to 3D
arr=np.array([[1, 2],
              [3, 4]])
arr.reshape(2,1,2)

array([[[1, 2]],

       [[3, 4]]])

In [60]:
#Converting 3D to 2D
arr=np.array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [62]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[10 12 14 16]
 [18 20 22 24]]
[[10 12 14 16]
 [18 20 22 24]]


In [64]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(arr2-arr1)
print(np.subtract(arr2,arr1))

[[8 8 8 8]
 [8 8 8 8]]
[[8 8 8 8]
 [8 8 8 8]]


In [65]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[  9  20  33  48]
 [ 65  84 105 128]]
[[  9  20  33  48]
 [ 65  84 105 128]]


In [67]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[9,10,11,12],[13,14,15,16]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[0.11111111 0.2        0.27272727 0.33333333]
 [0.38461538 0.42857143 0.46666667 0.5       ]]
[[0.11111111 0.2        0.27272727 0.33333333]
 [0.38461538 0.42857143 0.46666667 0.5       ]]


In [72]:
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(np.sqrt(arr1))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [71]:
arr1=np.array([[3,4,6,1],[8,3,6,9]])
print(np.sort(arr1))

[[1 3 4 6]
 [3 6 8 9]]


# Slicing

In [73]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[0:2])

[1 2]


In [74]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [75]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[2:])

[3 4 5 6 7]


In [76]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:])

[5 6 7]


In [77]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [78]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1:3,2])

[8]
