In [56]:
!pip install numpy

# 1D Array

In [57]:
import numpy as np

arr=np.array([1,2,3])
print(arr)

[1 2 3]


# 2D Array

In [58]:
arr=np.array([(1,2,3),(4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


# 3D Array

In [59]:
arr=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


# 4D Array

In [60]:
arr=np.array([[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]])
print(arr)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]


 [[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]


# 5D Array

In [61]:
arr=np.array([[[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]],[[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]]])
print(arr)

[[[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]


  [[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]



 [[[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]


  [[[ 1  2  3]
    [ 4  5  6]]

   [[ 7  8  9]
    [10 11 12]]]]]


# Initial Placeholders

In [62]:
#Create an array of zeros
arr=np.array(np.zeros(3))
print(arr)

[0. 0. 0.]


In [63]:
arr=np.array(np.zeros((3,4)))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [64]:
arr=np.array(np.zeros((2,3,4)))
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [65]:
#Create an array of ones
arr=np.array(np.ones((2,3,4)))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [66]:
#Create an array of evenly spaced values (step value)
a=np.arange(5,25,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23]


In [67]:
#Create an array of evenlyspaced values (number of samples)
b=np.linspace(1,10,10)
print(b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [68]:
#Create a constant array
#Create a 1D array
c=np.full((2,3),7)
print(c)
print(c.ndim)

[[7 7 7]
 [7 7 7]]
2


In [69]:
d=np.full((2,2,3),7)
print(d)
print(d.ndim)

[[[7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]]]
3


In [70]:
#Create a 2X2 identity matrix
e=np.eye(1)
print(e)

[[1.]]


In [71]:
e=np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


In [72]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [73]:
#Create an array with random values
np.random.random(3)

array([0.73586211, 0.24996136, 0.35146621])

In [74]:
np.random.random((3,4))

array([[0.46224719, 0.13265373, 0.54320631, 0.8936076 ],
       [0.15175231, 0.42589717, 0.38657126, 0.70301032],
       [0.70396674, 0.36252468, 0.68515211, 0.54925472]])

In [75]:
np.random.random((2,3,4))

array([[[0.07084365, 0.47801228, 0.0165836 , 0.16909236],
        [0.82981445, 0.29708973, 0.80280216, 0.10135062],
        [0.35900442, 0.12319441, 0.93066777, 0.13405141]],

       [[0.33974497, 0.15271246, 0.83770737, 0.18059252],
        [0.80765105, 0.05712549, 0.2357579 , 0.51531473],
        [0.62939844, 0.79994682, 0.59208914, 0.05080264]]])

In [76]:
arr=np.array([1,2,3])
print(arr.shape) #to find shape of an Array i.e (no. of rows,no. of cols)
print(arr.size) #To Find NO of elements in array
len(arr) #To Find len of array i.e # It Will count only the rows

(3,)
3


3

In [77]:
arr=np.array([(1,2,3),(4,5,6)])
print(arr.shape)
print(arr.size)
len(arr)

(2, 3)
6


2

In [78]:
arr=np.array([[(1,2,3),(4,5,6)],
 [(7,8,9),(10,11,12)]])
print(arr.shape)
print(arr.size)
len(arr)

(2, 2, 3)
12


2

In [79]:
arr=np.array([[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],
 [[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]])
print(arr.shape)
print(arr.size)
len(arr)

(2, 2, 2, 3)
24


2

In [80]:
arr=np.array([[[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]],
 [[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]],[[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]]]])
print(arr.shape)
print(arr.size)
len(arr)

(2, 2, 2, 2, 3)
48


2

In [81]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [5, 7, 7, 8]])
print(arr.shape)
print(arr.size)
len(arr)

(3, 4)
12


3

In [82]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [5, 6, 7, 8],
                [5, 7, 7, 8]])
print(arr.shape)
print(arr.size)
len(arr)

(4, 4)
16


4

In [83]:
np.random.randint(5,8)

5